# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# https://goreleaser.com/customization/build/
project_name: proxycheck
gomod:
  proxy: true
builds:
  - env: [CGO_ENABLED=0]
    binary: proxycheck
    main: ./main.go
    ldflags:
        - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.Date={{.Date}} -X main.Branch={{.Branch}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - maintainer: becivells
    description: judas
    homepage: https://github.com/Becivells/wsproxycheck
    license: MIT
    formats:
      - deb
      - rpm